[package]
name = "rust_glass"
version = "0.1.0"
authors = ["Sullivan B"]
description = "Dynamically typed language written in RustLang"
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
clap = "2.33.3"
atty = "0.2.14"
strum = "0.21"
strum_macros = "0.21"
git-version = "0.3.5"